import React from "react";
import { useRouter } from "next/router";

import Room from "./ColabSpace";
import Head from "next/head";

const Space = () => {
  const router = useRouter();
  console.log(router.query);
  return (
    <>
      <Head>
        <title>Colab Space </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Room />
      </main>
    </>
  );
};

export default Space;
