import Head from "next/head";
import Login from "./login";
import Register from "./register";



export default function Landing() {
  return (
    <>
      <Head>
        <title>login </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Login />
        {/* <Register /> */}
      </main>
    </>
  );
}