import Toast from "@/components/toast/Toast";
import Head from "next/head";
import Home from "./home/Home";


export default function Landing() {
  return (
    <>
      <Head>
        <title>e-cast </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Home />
      </main>
    </>
  );
}